apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.project.deploy.name }}-service
  labels:
    app: {{ .Values.project.deploy.name }}
spec:
  type: {{ .Values.project.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.project.service.servicePort }}
{{- if .Values.project.service.targetPort }}    
    targetPort: {{ .Values.project.service.targetPort }}
{{- end }}
{{- if (and (eq .Values.project.service.servicetype "NodePort") (not (empty .Values.project.service.nodePort )))}}
    nodePort: {{ .Values.project.service.nodePort }}
{{- end }}
    name: {{ .Values.project.service.name }}
  selector:
    app: {{ .Values.project.deploy.name }}
