def deployName = "test"
def deployNamespace = ""
def imageName = "localhost:32000/kubectl"
def imageTag = "1.1"
def podReplicaCount = "3"
def serviceType = "ClusterIP" // None, NodePort, ClusterIP, LoadBalancer
def servicePorts = []

podTemplate(cloud: 'kubernetes', containers: [
    containerTemplate(
        name: 'kubectl',
        image: 'localhost:32000/kubectl:1.1',
        ttyEnabled: true,
        privileged: false,
        alwaysPullImage: false,
        workingDir: '/home/jenkins/agent',
        resourceRequestCpu: '50m',
        resourceLimitCpu: '100m',
        resourceRequestMemory: '100Mi',
        resourceLimitMemory: '200Mi',
        command: 'cat'
    )
],
volumes: [
    configMapVolume(mountPath: '/home/jenkins/agent/.kube', configMapName: 'jenkins-cluster-master')
]
) {
  node(POD_LABEL)  {
    stage('Run maven') {
        container('kubectl') {
            checkout scm
            sh "helm template --set project.name=${deployName},project.namespace=test,project.deploy.name=test,project.pod.image.name=test,project.pod.image.tag=1.0 k8s/helm/basic/chart/"
        }
    }
  }
}
